repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.9
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: env PYTHONPATH=. pytest
      args: ["-q"]
      language: system
      pass_filenames: false
      always_run: true
