"""add Article

Revision ID: 60aa2496c42f
Revises: fffe19c1f708
Create Date: 2025-09-08 13:57:07.200678

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60aa2496c42f"
down_revision: Union[str, Sequence[str], None] = "fffe19c1f708"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("authors", sa.JSON(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column(
            "publication_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("journal", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("volume", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("issue", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pages", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "publication_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("doi", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pmid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pmcid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("issn", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=True),
        sa.Column("mesh_terms", sa.JSON(), nullable=True),
        sa.Column("article_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_text_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("urls", sa.JSON(), nullable=True),
        sa.Column("full_text_retrieved", sa.Boolean(), nullable=False),
        sa.Column("full_text_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ai_check_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ai_check_result", sa.JSON(), nullable=True),
        sa.Column("last_ai_check", sa.DateTime(), nullable=True),
        sa.Column("source_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_article_ai_check_status"), "article", ["ai_check_status"], unique=False
    )
    op.create_index(op.f("ix_article_doi"), "article", ["doi"], unique=True)
    op.create_index(
        op.f("ix_article_full_text_retrieved"),
        "article",
        ["full_text_retrieved"],
        unique=False,
    )
    op.create_index(op.f("ix_article_issn"), "article", ["issn"], unique=False)
    op.create_index(op.f("ix_article_journal"), "article", ["journal"], unique=False)
    op.create_index(op.f("ix_article_pmcid"), "article", ["pmcid"], unique=True)
    op.create_index(op.f("ix_article_pmid"), "article", ["pmid"], unique=True)
    op.create_index(
        op.f("ix_article_project_id"), "article", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_article_title"), "article", ["title"], unique=False)
    op.create_index(op.f("ix_article_year"), "article", ["year"], unique=False)
    op.create_index(op.f("ix_project_name"), "project", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_name"), table_name="project")
    op.drop_index(op.f("ix_article_year"), table_name="article")
    op.drop_index(op.f("ix_article_title"), table_name="article")
    op.drop_index(op.f("ix_article_project_id"), table_name="article")
    op.drop_index(op.f("ix_article_pmid"), table_name="article")
    op.drop_index(op.f("ix_article_pmcid"), table_name="article")
    op.drop_index(op.f("ix_article_journal"), table_name="article")
    op.drop_index(op.f("ix_article_issn"), table_name="article")
    op.drop_index(op.f("ix_article_full_text_retrieved"), table_name="article")
    op.drop_index(op.f("ix_article_doi"), table_name="article")
    op.drop_index(op.f("ix_article_ai_check_status"), table_name="article")
    op.drop_table("article")
    # ### end Alembic commands ###
