"""add full_text_content to article

Revision ID: 9bc80ee934e2
Revises: f589762b3834
Create Date: 2026-02-03 18:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bc80ee934e2"
down_revision: Union[str, Sequence[str], None] = "f589762b3834"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("article", sa.Column("full_text_content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("article", "full_text_content")
    # ### end Alembic commands ###
